name: Deploy Original

on:
  push:
    branches: [ "original" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install and build
      run: |
        npm install
        npm run build

    - name: Deploy
      run: |
        pushd ${{ github.workspace }}/dist
        tar -cvzf ${{ github.workspace }}/sapi-doc.tar.gz *
        popd
        echo "${{ secrets.SSH_KEY }}" > ${{ github.workspace }}/key.txt
        chmod 400 ${{ github.workspace }}/key.txt
        scp -q -P ${{ secrets.PORT }} -o StrictHostKeyChecking=no -i ${{ github.workspace }}/key.txt ${{ github.workspace }}/sapi-doc.tar.gz "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}":/tmp/sapi-doc.tar.gz
        ssh -q -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no -i ${{ github.workspace }}/key.txt "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}" "rm -rf ${{ secrets.TARGET_PATH_ORIGINAL }}/* && tar -xvzf /tmp/sapi-doc.tar.gz -C ${{ secrets.TARGET_PATH_ORIGINAL }} && rm -f /tmp/sapi-doc.tar.gz"
        rm ${{ github.workspace }}/key.txt
