name: Deploy Original

on:
  push:
    branches: [ "original" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Deploy
      run: |
        echo "${{ secrets.SSH_KEY }}" > key.txt
        chmod 400 key.txt
        scp -pqrO -P ${{ secrets.PORT }} -o StrictHostKeyChecking=no -i key.txt ./dist/* "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}":${{ secrets.TARGET_PATH_ORIGINAL }}
        rm key.txt
