name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install and build
      run: |
        npm install
        npm run build

    - name: Deploy to self-hosted site
      run: |
        pushd ${{ github.workspace }}/dist
        tar -cvzf ${{ github.workspace }}/sapi-doc.tar.gz *
        popd
        echo "${{ secrets.SSH_KEY }}" > ${{ github.workspace }}/key.txt
        chmod 400 ${{ github.workspace }}/key.txt
        scp -q -P ${{ secrets.PORT }} -o StrictHostKeyChecking=no -i ${{ github.workspace }}/key.txt ${{ github.workspace }}/sapi-doc.tar.gz "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}":/tmp/sapi-doc.tar.gz
        ssh -q -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no -i ${{ github.workspace }}/key.txt "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}" "rm -rf ${{ secrets.TARGET_PATH }}/* && tar -xvzf /tmp/sapi-doc.tar.gz -C ${{ secrets.TARGET_PATH }} && rm -f /tmp/sapi-doc.tar.gz"
        rm ${{ github.workspace }}/key.txt
    
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact to GitHub pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{ github.workspace }}/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
